INSERT IGNORE INTO roles(id,name) VALUES(1,'ROLE_USER');
INSERT IGNORE INTO roles(id,name) VALUES(2,'ROLE_ADMIN');
INSERT IGNORE INTO roles(id,name) VALUES(3,'ROLE_SUPERADMIN');

TRUNCATE TABLE jwt_session;